-- MySQL Script generated by MySQL Workbench
-- Sat Oct 11 14:33:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_inventario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_inventario` ;

-- -----------------------------------------------------
-- Schema bd_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_inventario` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_inventario` ;

-- -----------------------------------------------------
-- Table `bd_inventario`.`articulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`articulos` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`articulos` (
  `Id_Articulo` INT NOT NULL,
  `Id_Insumo_Art` INT NOT NULL,
  `Nom_Articulo` VARCHAR(120) NOT NULL,
  `Tempo_Siembra_Art` VARCHAR(1) NOT NULL COMMENT 'P = Primavera\\\\nV = Verano\\\\nO = Otoño\\\\nI = Invierno\\\\nT = Todas',
  `Tempo_Cosecha_Art` VARCHAR(1) NOT NULL COMMENT 'P = Primavera\\\\nV = Verano\\\\nO = Otoño\\\\nI = Invierno\\\\nT = Todas',
  `Inventario_Art` INT NOT NULL,
  `Precio_Venta_Art` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`Id_Articulo`, `Id_Insumo_Art`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tablas de Articulos';


-- -----------------------------------------------------
-- Table `bd_inventario`.`compra_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`compra_detalle` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`compra_detalle` (
  `Id_Compra` INT NOT NULL,
  `Id_Insumo_Compra` INT NOT NULL,
  `Cantidad_Compra` INT NOT NULL DEFAULT '0',
  `Precio_Compra` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`Id_Compra`, `Id_Insumo_Compra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de la compra de insumos';


-- -----------------------------------------------------
-- Table `bd_inventario`.`compra_encab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`compra_encab` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`compra_encab` (
  `Id_Compra` INT NOT NULL,
  `Id_Proveedor_Compra` INT NOT NULL,
  `Subtotal_Compra` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `IVA_Compra` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Total_Compra` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Desc_Prov_Compra` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Gran_Total_Compra` DECIMAL(10,2) NOT NULL,
  `Status_Compra` VARCHAR(1) NOT NULL DEFAULT 'P' COMMENT 'P = Pendiente\\nS = Surtido',
  PRIMARY KEY (`Id_Compra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla para generar orden de compra de los insumos';


-- -----------------------------------------------------
-- Table `bd_inventario`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`empleados` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`empleados` (
  `Id_Empleado` INT NOT NULL,
  `Nom_Empleado` VARCHAR(120) NOT NULL,
  `Calle_Emp` VARCHAR(100) NOT NULL,
  `Num_Ext_Emp` INT NULL DEFAULT NULL,
  `Fecha_Nac_Emp` DATE NOT NULL,
  `Codigo_Postal_Emp` DECIMAL(7,0) NOT NULL,
  `Colonia_Emp` VARCHAR(120) NOT NULL,
  `Ciudad_Emp` VARCHAR(120) NOT NULL,
  `Estado_Emp` VARCHAR(120) NOT NULL,
  `Telefono1_Emp` VARCHAR(20) NULL DEFAULT NULL,
  `Telefono2_Emp` VARCHAR(20) NULL DEFAULT NULL,
  `Comision_Emp` DECIMAL(5,2) NOT NULL,
  `CURP_Emp` VARCHAR(30) NOT NULL,
  `RFC_Emp` VARCHAR(20) NOT NULL,
  `E_Mail_Emp` VARCHAR(100) NULL DEFAULT NULL,
  `Fecha_Contrato_Emp` DATE NOT NULL,
  `Status_Emp` VARCHAR(6) NOT NULL DEFAULT 'A' COMMENT 'A = Activo\\\\\\\\nB = Baja',
  `Sexo_Emp` VARCHAR(1) NOT NULL COMMENT 'M = Masculino\\\\nF = Femenino',
  PRIMARY KEY (`Id_Empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de Empleados Vendedores por Comision';


-- -----------------------------------------------------
-- Table `bd_inventario`.`facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`facturas` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`facturas` (
  `Id_Factura` INT NOT NULL,
  `Id_Venta_fact` INT NOT NULL,
  PRIMARY KEY (`Id_Factura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de Facturas Generadas';


-- -----------------------------------------------------
-- Table `bd_inventario`.`insumos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`insumos` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`insumos` (
  `Id_Insumo` INT NOT NULL,
  `Id_Proveedor_Ins` INT NOT NULL,
  `Nom_Insumo` VARCHAR(120) NOT NULL,
  `Punto_Reorden_Ins` INT NOT NULL DEFAULT '0',
  `Inventario_Ins` INT NOT NULL DEFAULT '0',
  `Precio_Compra_Ins` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Id_Insumo`, `Id_Proveedor_Ins`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de Insumos(Materiales para Producir un bien o producto)';


-- -----------------------------------------------------
-- Table `bd_inventario`.`mercados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`mercados` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`mercados` (
  `Id_Mercado` INT NOT NULL,
  `Nom_Mercado` VARCHAR(120) NOT NULL,
  `Calle_Merc` VARCHAR(100) NOT NULL,
  `Num_Ext_Merc` INT NOT NULL,
  `Fecha_Ingreso_Merc` DATE NOT NULL,
  `Codigo_Postal_Merc` DECIMAL(7,0) NOT NULL,
  `Colonia_Merc` VARCHAR(120) NOT NULL,
  `Ciudad_Merc` VARCHAR(120) NOT NULL,
  `Estado_Merc` VARCHAR(120) NOT NULL,
  `Telefono1_Merc` VARCHAR(20) NULL DEFAULT NULL,
  `Telefono2_Merc` VARCHAR(20) NULL DEFAULT NULL,
  `RFC_Merc` VARCHAR(20) NOT NULL,
  `E_Mail_Merc` VARCHAR(100) NULL DEFAULT NULL,
  `Descuento_Merc` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Min 0% max 50%',
  PRIMARY KEY (`Id_Mercado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_inventario`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`proveedores` (
  `Id_Proveedor` INT NOT NULL,
  `Nom_Proveedor` VARCHAR(120) NOT NULL,
  `Calle_Prov` VARCHAR(100) NOT NULL,
  `Num_Ext_Prov` INT NOT NULL,
  `Fecha_Ingreso_Prov` DATE NOT NULL,
  `Codigo_Postal_Prov` DECIMAL(7,0) NOT NULL,
  `Colonia_Prov` VARCHAR(120) NOT NULL,
  `Ciudad_Prov` VARCHAR(120) NOT NULL,
  `Estado_Prov` VARCHAR(120) NOT NULL,
  `Telefono1_Prov` VARCHAR(20) NULL DEFAULT NULL,
  `Telefono2_Prov` VARCHAR(20) NULL DEFAULT NULL,
  `RFC_Prov` VARCHAR(20) NOT NULL,
  `E_Mail_Prov` VARCHAR(100) NULL DEFAULT NULL,
  `Descuento_Prov` DECIMAL(5,2) NOT NULL DEFAULT '0.00' COMMENT 'Min 0% max 50%',
  PRIMARY KEY (`Id_Proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_inventario`.`saldo_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`saldo_empresa` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`saldo_empresa` (
  `Fecha_Saldo` DATE NOT NULL,
  `Saldo_Empresa` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`Fecha_Saldo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Saldo Diario con que empieza en Caja Chica, Si son Negativos se cobra a Cajera';


-- -----------------------------------------------------
-- Table `bd_inventario`.`venta_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`venta_detalle` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`venta_detalle` (
  `Id_Venta` INT NOT NULL,
  `id_Articulo_vta` INT NOT NULL,
  `Cantidad_Vta` INT NOT NULL DEFAULT '0',
  `Precio_Vta` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`Id_Venta`, `id_Articulo_vta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla donde se encuentran los articulos vendidos';


-- -----------------------------------------------------
-- Table `bd_inventario`.`venta_encab`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_inventario`.`venta_encab` ;

CREATE TABLE IF NOT EXISTS `bd_inventario`.`venta_encab` (
  `Id_Venta` INT NOT NULL,
  `Id_Mercado_Vta` INT NOT NULL,
  `Id_Empleado_Vta` INT NOT NULL,
  `Subtotal_Vta` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `IVA_Vta` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Total_Vta` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Desc_Merc_Vta` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Gran_Total_Vta` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `Comision_Emp_Vta` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Id_Venta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Tabla de Encabezado de Ventas';

USE `bd_inventario` ;

-- -----------------------------------------------------
-- procedure Conteo_de_ciudades
-- -----------------------------------------------------

USE `bd_inventario`;
DROP procedure IF EXISTS `bd_inventario`.`Conteo_de_ciudades`;

DELIMITER $$
USE `bd_inventario`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Conteo_de_ciudades`( IN var_estado INT, OUT conteo_ciudades INT)
BEGIN
	SELECT count(*) into conteo_ciudades FROM cuidades where Id_Estado = var_estado ;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Reporte_Listado_Articulos
-- -----------------------------------------------------

USE `bd_inventario`;
DROP procedure IF EXISTS `bd_inventario`.`Reporte_Listado_Articulos`;

DELIMITER $$
USE `bd_inventario`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Reporte_Listado_Articulos`()
BEGIN
SELECT A.id_articulo as ID_ART,
    A.nom_articulo as Nombre_Art,
    A.Precio_Venta_Art as Precio_Venta,
    I.id_insumo as Num_Insumo,
    I.Nom_Insumo as Nombre_Ins,
    I.Punto_Reorden_Ins as Reorden,
    I.Inventario_Ins as Inventario,
    P.Nom_Proveedor as Proveedor,
    I.Precio_Compra_Ins as Precio_Ins
    FROM articulos A, Insumos I, Proveedores P
    WHERE I.id_insumo = A.Id_insumo_Art AND 
	P.Id_Proveedor = I.Id_Proveedor_Ins
    ORDER BY A.Id_Articulo ASC, I.id_insumo ASC;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `bd_inventario`;

DELIMITER $$

USE `bd_inventario`$$
DROP TRIGGER IF EXISTS `bd_inventario`.`articulos_BEFORE_INSERT` $$
USE `bd_inventario`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `bd_inventario`.`articulos_BEFORE_INSERT`
BEFORE INSERT ON `bd_inventario`.`articulos`
FOR EACH ROW
BEGIN
/*Checa que el Articulo No tenga mas de 10 Insumos Asignados*/
    IF (	SELECT COUNT(*)
				FROM Articulos
				WHERE Id_Articulo = new.id_Articulo
				GROUP BY Id_Articulo)>10 THEN
        SIGNAL SQLSTATE "45000"
        SET MESSAGE_TEXT = "No se puede Agregar mas de 10 Insumos por Articulo";
	END IF;
END$$


USE `bd_inventario`$$
DROP TRIGGER IF EXISTS `bd_inventario`.`insumos_BEFORE_INSERT` $$
USE `bd_inventario`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `bd_inventario`.`insumos_BEFORE_INSERT`
BEFORE INSERT ON `bd_inventario`.`insumos`
FOR EACH ROW
BEGIN	
	/*Checa que el Insumo No tenga mas de 10 Proveedores Asignados*/
    IF (	SELECT COUNT(*)>10
				FROM Insumos
				WHERE Id_insumo = new.id_insumo
				GROUP BY Id_insumo) >10 THEN
        SIGNAL SQLSTATE "45000"
        SET MESSAGE_TEXT = "No se puede Agregar mas de 10 Proveedores por Insumo";
	END IF;
END$$


DELIMITER ;
